version: 2
jobs:
  build-all:
    machine: true
    working_directory: ~/start.eventuate.io
    steps:
      - checkout
      - run: TERM=dumb sudo npm install -g node-gyp
      - run: TERM=dumb ./build-all.sh
      - run: TERM=dumb ./download-and-build-example.sh
      - run:
          name: Save build results
          command: |
            mkdir -p ~/container-logs
          when: always
      - store_artifacts:
          path: ~/container-logs
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-all
