version: 2
jobs:
  build:
#    machine: true
    docker:
      - image: circleci/openjdk:8u232-node
    working_directory: ~/start.eventuate.io
    steps:
      - checkout
      - setup_remote_docker
      - run: TERM=dumb ./build-all.sh
      - run: TERM=dumb ./download-and-build-example.sh
      - run:
          name: Save containers and test results
          command: ./.circleci/save-containers-and-tests.sh
          when: always
      - store_artifacts:
          path: ~/container-logs
